version: '3'

services:
  database:
    image: mysql
    container_name: mysql
    hostname: cucumbers
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: cucumdb
      MYSQL_USER: cucumber
      MYSQL_PASSWORD: 1234
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql  # Maps ./mysql directory to MySQL data storage

volumes:
  mysql-data:

